### ISSUE TITLE
use only one babel config: Error

### ISSUE THREAD

**Issue by bahtou** [scrapd/scrapdviz#112]
Running dev locally is throwing a babel error

Issue Type
----------
- Bug report

Current Behavior
----------------
when running `npm run dev` this error appears
```
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: Multiple configuration files found. Please remove one:
 - package.json#babel
 - .babelrc
```

Expected Behavior
-----------------
The application should run locally without issue when invoked with `npm run dev` 

Possible Solution
-----------------
Not sure which babel configuration is favored. There is a `babel` key in `package.json` and a separate `.babelrc` file. I removed the `babel` config from the `package.json` and the application is running without issues. But not really sure which configuration the project favors.

Steps to Reproduce
-----------------
1. fetched & merged latest master
2. `npm i`
3. `npm run dev`

**Comment by rgreinho** [comment]
There is no `babel.rc` file in the code base, we put all the configuration in the `package.json` file. 

Try the following to clean your code base:
1. git checkout master
2. git clean -d -f -x && git reset --hard
3. git pull
4. npm i
5. npm run dev

**Comment by bahtou** [comment]
that worked
thank you
