### ISSUE TITLE
Update queries for ScrAPD 3 format

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapdviz#148]
Issue Type
----------

- Bug report
- Feature request

Current Behavior
----------------

The queries are made for ScrAPD 2.

Expected Behavior
-----------------

The queries must be updated for ScrAPD 3.

Possible Solution
-----------------

Flatten the entry based on the number of fatalities.

**Comment by tom-nook** [comment]
I remember you telling me about this and I remember seeing a function and hearing about flattening, but tbh I think I need to ask about this again :disappointed:

**Comment by rgreinho** [comment]
Hehe, you memorized all terms right, now we just need to implement this specific function 😉 

We could work on it together and I'll drive you through the process 👍

**Comment by rgreinho** [comment]
Fixed by @tom-nook.
