### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapdviz#15]
Issue Type
----------

- Feature request

Current Behavior
----------------

There is currently no way to download the data set from ScrAPDviz.

Expected Behavior
-----------------

Provide the user that ability to download the part of the data set he/she is viewing. The available formats should be at least CSV and JSON,.

**Comment by rgreinho** [comment]
Useful resources:

* https://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server
* https://ourcodeworld.com/articles/read/189/how-to-create-a-file-and-generate-a-download-with-javascript-in-the-browser-without-a-server

**Comment by jarrmill** [comment]
Hey Remi, would you mind if I took a crack at this issue?

**Comment by rgreinho** [comment]
No problem! I'm assigning it to you @jarrmill.

**Comment by jarrmill** [comment]
Hey @rgreinho, a quick design question. I have the functionality for this ticket ready to go, but wanted to get your preference on the layout.

<img width="1007" alt="Screen Shot 2019-05-31 at 11 19 33 AM" src="https://user-images.githubusercontent.com/15021477/58729901-406ed980-83b0-11e9-95ef-a48be388b871.png">

<img width="1004" alt="Screen Shot 2019-05-31 at 2 27 12 PM" src="https://user-images.githubusercontent.com/15021477/58729911-45cc2400-83b0-11e9-8662-0d1cd019affe.png">

On the first, we have four buttons - two for copy & downloading CSV, and two for copy & downloading JSON.

On the second, we can have a radio button that lets the user select JSON and CSV, and a copy and download button that will download whichever data type the user has selected.

Let me know what you think, or if there is anything else I should try out instead. Thanks!

**Comment by rgreinho** [comment]
Wow, awesome work @jarrmill! 

I would say I prefer the first approach. You could try removing the "Download" word, as the icon is explicit enough. That was my reasoning with the copy icons.

Our main use case is users copying the content in CSV format. This must stay the main or "default" action. I feel like this is less clear with the radio buttons.

**Comment by jarrmill** [comment]
@rgreinho great points. I'll put some finishing touches on the first approach and try to have a pull request soon. Thanks!

**Comment by rgreinho** [comment]
Closee by #103.
