### ISSUE TITLE
Update grid columns in the APD view

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapdviz#159]
Issue Type
----------

- Feature request

Current Behavior
----------------

Expected Behavior
-----------------

* Group **ALL** the names (first, middle and last) under 1 `Name` column
* Remove the `DOB` column (the age is what is really used).
* Rename `Crash date` to simply `Date`
* Rename `Crash time` to simply `Time`

### Additional information:

If we decide that more space is needed in the grid, the `Case` column could also go away and the link would be put in the `Crash` column.

**Comment by tom-nook** [comment]
Reviewing!

**Comment by rgreinho** [comment]
Claimed by @tom-nook.

**Comment by tom-nook** [comment]
Attempted this in on a [branch](https://github.com/tom-nook/scrapdviz/commits/issue_159) on my fork

**Comment by rgreinho** [comment]
Fixed by #171.
