### ISSUE TITLE
Review home page copy

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapdviz#165]
Issue Type
----------

- Feature request

Current Behavior
----------------

Expected Behavior
-----------------

Review the home page copy to ensure it conveys the right message.

**Comment by tom-nook** [comment]
Attempted this in on a [branch](https://github.com/tom-nook/scrapdviz/commits/issue_165) on my fork

**Comment by rgreinho** [comment]
Fixed by #168.
