### ISSUE TITLE
Replace Hero image

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapdviz#184]
Issue Type
----------

- Bug report
- Feature request

Current Behavior
----------------

It is kind of a bug and a feature at the same time.

The image used for the hero is too big: 2.2MB! We should try to divide the size of the image by 2. That would be a good goal.

The other problem is that the picture represents a car, and for an app promoting vision zero, that's not ideal.

Expected Behavior
-----------------

* Reduce the size of the Hero image (toward ~1.1MB)
* Choose an image more aligned with our mission

Possible Solution
-----------------

* Examples of other images we could use:

 |License|Reason| Link|
|---|---|---|
|CC0|A nice picture of Amsterdam. While the focus is on bikes, is also depicts cars and pedestrian in a pleasant atmosphere.|https://pxhere.com/en/photo/646444|
|CC-BY|A very nice picture of a main street, on a regular day in  Madison, WI|https://www.flickr.com/photos/rahimageworks/11444763193|
|CC_BY_NC_ND|Interesting picture of Earth day in NYC where the street is closed for the fair|https://www.flickr.com/photos/nycstreets/34226513652/|
|CC-BY|:star2: This one is my favorite!  :star2: It shows a big city, with people walking and biking, as well as a dedicated bus lane! 🚶‍♀  :bike: :bus: |https://commons.wikimedia.org/wiki/File:Jakarta_Car_Free_Day.jpg|

**Comment by tom-nook** [comment]
Working on this in #185
