### ISSUE TITLE
Misc. fixes for Hero Image

### ISSUE THREAD

**Issue by tom-nook** [scrapd/scrapdviz#186]
Issue Type
----------

- Bug report

Current Behavior
----------------

Currently at a mobile screen dimension, the hero image is:
- Repeating
- Not sized properly

No credit given for image, found [here](https://commons.wikimedia.org/wiki/File:Jakarta_Car_Free_Day.jpg)

Expected Behavior
-----------------

Hero image should be responsive, proper display on mobile screen dimensions.

Credits should be provided for image.

Possible Solution
-----------------

Media queries with Emotion should address this. Documentation [here](https://emotion.sh/docs/media-queries).

Steps to Reproduce
------------------

1. Open home page
2. Resize screen width to under a width of 750px or under.

Context
-------

The hero image is unsightly for users on mobile devices.

**Comment by tom-nook** [comment]
Working on in [forked repo](https://github.com/tom-nook/scrapdviz/tree/scrapd3/186).

**Comment by tom-nook** [comment]
Work on this issue is complete! I believe the last time, there was another branch on the project (not master) to which I made pull requests...am I remembering that right? 

Also I just happened to have some time this break to work on this, this can wait til after the break/January.

**Comment by rgreinho** [comment]
You are remembering correctly. But it was because we were working on a series of big changes so we created a long term branch where we could potentially mess up things without affecting `master` and production.

Now you can safely base your work on master.

**Comment by rgreinho** [comment]
<https://www.responsivebreakpoints.com/> generates responsive images, provides all the sizes and HTML5 snippets to include in the code.
